baseURL = 'https://ejkhub.github.io/183-river-ridge-ct/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[params]
  description = 'Follow our journey building our dream home at River Ridge'